<!doctype html>
<html>
  <head>
    <title>Tabelki</title>
  </head>
    <body>
      <table>
        <table border="1">
        <tr>
          <th>1</th>
          <th>2</th>
          <th>3</th>
          <th>4</th>
          <th>5</th>
          <th>6</th>
        </tr>
        <tr>
          <th>2</th>
          <td>a</td>
          <td>b</td>
          <td>c</td>
          <td>d</td>
          <td>e</td>
        </tr>
        <tr>
          <th>3</th>
          <td>f</td>
          <td>g</td>
          <td>h</td>
          <td>i</td>
          <td>j</td>
        </tr>
        <tr>
          <th>4</th>
          <td>k</td>
          <td>l</td>
          <td>m</td>
          <td>n</td>
          <td>o</td>
        </tr>
        <tr>
          <th>5</th>
          <td>p</td>
          <td>q</td>
          <td>r</td>
          <td>s</td>
          <td>t</td>
        </tr>
        <tr>
          <th>6</th>
          <td>u</td>
          <td>v</td>
          <td>w</td>
          <td>y</td>
          <td>z</td>
        </tr>
      </table>
      <table>
        <table border="1">
        <tr>
          <th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th>
        </tr>
        <tr>
          <th>2</th><td>a</td><td colspan="2">b, c</td><td>d</td><td>e</td>
        </tr>
        <tr>
          <th>3</th><td>f</td><td>g</td><td>h</td><td>i</td><td rowspan="2">j, o</td>
        </tr>
        <tr>
          <th>4</th><td>k</td><td>l</td><td>m</td><td>n</td>
        </tr>
        <tr>
          <th>5</th><td colspan="3" rowspan="2">p, q, r,u, v, w</td><td>s</td><td>t</td>
        </tr>
        <tr>
          <th>6</th><td>y</td><td>z</td>
        </tr>
      </table>
      <table>
        <table border="1">
        <tr>
          <th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th>
        </tr>
        <tr>
          <th>2</th><td>a</td><td>b</td><td>c</td><td>d</td><td>e</td>
        </tr>
        <tr>
          <th>3</th><td>f</td><td>g</td><td>h</td><td>i</td><td>j</td>
        </tr>
        <tr>
          <th>4</th><td>k</td><td>l</td><td>m</td><td>n</td><td>o</td>
        </tr>
        <tr>
          <th>5</th><td rowspan="2">PP, u</td><td>q</td><td>r</td><td>s</td><td>t</td>
        </tr>
        <tr>
          <th>6</th><td>v</td><td>w</td><td>y</td><td>z</td>
        </tr>
      </table>
    </body>
  </html>
